# Generated by Django 4.1.6 on 2023-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specie', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
