# Generated by Django 4.2.7 on 2023-12-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_vaccine_pet_vacciness'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('prescription', models.TextField()),
            ],
        ),
    ]
