# Generated by Django 4.2.7 on 2023-12-04 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vacciness',
        ),
        migrations.AddField(
            model_name='pet',
            name='vacciness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main.vaccine'),
        ),
    ]
