# Generated by Django 4.2.7 on 2023-12-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_pet_vacciness_pet_vacciness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
