# Generated by Django 4.2.7 on 2023-12-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_history_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
