# Generated by Django 4.2.7 on 2023-12-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pet_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='main.pet')),
            ],
        ),
    ]
